name: SpringDemo CI/CD
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Make .env file
        run: |
          cat > .env <<'EOF'
          ${{ secrets.ENV }}
          EOF

      - name: Install dependencies
        run: |
          pnpm install
          pnpm add styled-jsx @swc/helpers @next/env

      - name: Build with Next.js
        run: pnpm build

      - name: Copy modules not included in standalone
        run: |
          mkdir -p .next/standalone/node_modules/styled-jsx
          mkdir -p .next/standalone/node_modules/@swc/helpers
          mkdir -p .next/standalone/node_modules/@next/env
          cp -r ./node_modules/styled-jsx/* .next/standalone/node_modules/styled-jsx/ || true
          cp -r ./node_modules/@swc/helpers/* .next/standalone/node_modules/@swc/helpers/ || true
          cp -r ./node_modules/@next/env/* .next/standalone/node_modules/@next/env/ || true
          cp -r .next/static .next/standalone/.next/

      - name: Zip next
        run: zip -rq next.zip public .next/standalone

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.WAS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: SCP next to WAS
        run: |
          scp next.zip ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/

      - name: Unzip & restart Next.js
        run: |
          ssh ec2-user@${{ secrets.WAS }} '
            cd /home/ec2-user/workspace
            rm -rf frontend
            unzip -q next.zip -d frontend
            cp -r frontend/public frontend/.next/standalone/  
            cd /home/ec2-user/workspace/frontend/.next/standalone
            pm2 delete frontend || true
            pm2 start "node server.js" --name frontend
            pm2 save
          '
